# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.Count_Note:
    class: AppBundle\Services\CountNote
    arguments: ['@doctrine']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.MenuLike:
    class: AppBundle\Twig\MenuLikeExtension
    arguments: ['@app.Count_Note']
    tags:
        - { name: twig.extension}
